### ISSUE TITLE
viditut.com :)

### ISSUE THREAD

**Issue by mastad0n** [simon987/Misc-Download-Scripts#1]
Hey!

Not really an issue, just wondering if it's still running?
Looks like reddit removed the post.

:)

**Comment by simon987** [comment]
Most of the scripts 'threads' stalled while I was asleep. I got them back online but I won't be able to monitor them while I'm at work. I don't really have time to count but it should be about 60% done right now. Should be done be tonight if it doesn't crash again.

links.txt file is about 150Mb right now this is insane.

**Comment by simon987** [comment]
Alright. It finished scraping the links but when I tried to download they wouldn't work. To download the videos you need to pass some parameters in the link and I guess that these are only valid for a few hours. So the links.txt file (which is 260Mb now) is useless right now. To download the whole thing you would need to run the crawler script by yourself and download the videos quickly after the links are saved. One thing I discovered is that the scraping is a lot faster if you run multiple scripts at the same time: I splitted the courses.txt file in a bunch of smaller files and I ran one instance per file.

For now I'll modify the script so it will spew out all the links for a single course passed as a parameter or a constant in the script, that way I can only download the courses I need.

Sorry!
